use writ_parser::Visibility;
use writ_types::{ClassInfo, FieldInfo, MethodInfo, TraitInfo, Type, TypeRegistry};

use crate::type_map::writ_type_to_rust;

/// Generates Rust source code from Writ type declarations.
///
/// Produces struct definitions with `Deref`-based inheritance, trait
/// definitions, constructor `new()` methods, and `WritObject` implementations.
pub struct RustCodegen;

impl Default for RustCodegen {
    fn default() -> Self {
        Self::new()
    }
}

impl RustCodegen {
    pub fn new() -> Self {
        Self
    }

    /// Generate Rust source for all classes and traits in the registry.
    pub fn generate(&self, registry: &TypeRegistry) -> String {
        let mut out = String::new();

        // Header
        out.push_str("// Auto-generated by writ-codegen. Do not edit.\n\n");
        out.push_str("use std::collections::HashMap;\n");
        out.push_str("use writ_vm::Value;\n");
        out.push_str("use writ_vm::WritObject;\n\n");

        // Generate traits first (classes may implement them)
        let mut trait_names: Vec<&str> = registry.trait_names().collect();
        trait_names.sort();
        for name in &trait_names {
            if let Some(info) = registry.get_trait(name) {
                out.push_str(&self.generate_trait(info));
                out.push('\n');
            }
        }

        // Generate classes in dependency order (parents before children)
        let class_order = self.topological_class_order(registry);
        for name in &class_order {
            if let Some(info) = registry.get_class(name) {
                out.push_str(&self.generate_class(info, registry));
                out.push('\n');
            }
        }

        out
    }

    /// Generate Rust source for a single trait.
    pub fn generate_trait(&self, info: &TraitInfo) -> String {
        let mut out = String::new();

        out.push_str(&format!("pub trait {} {{\n", info.name));
        for method in &info.methods {
            let params = self.format_method_params(method);
            let ret = self.format_return_type(method);

            if method.has_default_body {
                out.push_str(&format!(
                    "    fn {name}({params}){ret} {{\n",
                    name = method.name
                ));
                out.push_str("        todo!(\"default body\")\n");
                out.push_str("    }\n");
            } else {
                out.push_str(&format!(
                    "    fn {name}({params}){ret};\n",
                    name = method.name
                ));
            }
        }
        out.push_str("}\n");

        out
    }

    /// Generate Rust source for a single class.
    pub fn generate_class(&self, info: &ClassInfo, registry: &TypeRegistry) -> String {
        let mut out = String::new();

        // Struct definition
        out.push_str(&self.generate_struct_def(info));

        // Deref/DerefMut impls for inheritance
        if let Some(ref parent) = info.parent {
            out.push_str(&self.generate_deref_impls(&info.name, parent));
        }

        // Constructor
        out.push_str(&self.generate_constructor(info, registry));

        // Methods
        if !info.methods.is_empty() {
            out.push_str(&self.generate_methods(info));
        }

        // Trait impls
        for trait_name in &info.traits {
            if let Some(trait_info) = registry.get_trait(trait_name) {
                out.push_str(&self.generate_trait_impl(info, trait_info));
            }
        }

        // WritObject impl
        out.push_str(&self.generate_writ_object_impl(info, registry));

        out
    }

    // ── Private helpers ──────────────────────────────────────────────

    fn generate_struct_def(&self, info: &ClassInfo) -> String {
        let mut out = String::new();
        out.push_str(&format!(
            "#[derive(Debug, Clone)]\npub struct {} {{\n",
            info.name
        ));

        // If extends, add a `base` field for the parent
        if let Some(ref parent) = info.parent {
            out.push_str(&format!("    base: {parent},\n"));
        }

        // Own fields only (inherited fields live in `base`)
        for field in &info.fields {
            let vis = if field.visibility == Visibility::Public {
                "pub "
            } else {
                ""
            };
            let ty = writ_type_to_rust(&field.ty);
            out.push_str(&format!("    {vis}{name}: {ty},\n", name = field.name));
        }

        out.push_str("}\n\n");
        out
    }

    fn generate_deref_impls(&self, child: &str, parent: &str) -> String {
        let mut out = String::new();

        out.push_str(&format!("impl std::ops::Deref for {child} {{\n"));
        out.push_str(&format!("    type Target = {parent};\n"));
        out.push_str(&format!(
            "    fn deref(&self) -> &{parent} {{ &self.base }}\n"
        ));
        out.push_str("}\n\n");

        out.push_str(&format!("impl std::ops::DerefMut for {child} {{\n"));
        out.push_str(&format!(
            "    fn deref_mut(&mut self) -> &mut {parent} {{ &mut self.base }}\n"
        ));
        out.push_str("}\n\n");

        out
    }

    fn generate_constructor(&self, info: &ClassInfo, registry: &TypeRegistry) -> String {
        let mut out = String::new();

        // Collect all fields in order: parent chain fields first, then own
        let all_fields = registry.all_fields(&info.name);

        out.push_str(&format!("impl {} {{\n", info.name));
        out.push_str("    pub fn new(");

        // Constructor params = all fields in order
        let params: Vec<String> = all_fields
            .iter()
            .map(|f| format!("{}: {}", f.name, writ_type_to_rust(&f.ty)))
            .collect();
        out.push_str(&params.join(", "));
        out.push_str(") -> Self {\n");

        if let Some(ref parent) = info.parent {
            // Separate parent fields from own fields
            let parent_fields = self.collect_parent_fields(info, registry);
            let parent_args: Vec<String> = parent_fields.iter().map(|f| f.name.clone()).collect();

            out.push_str("        Self {\n");
            out.push_str(&format!(
                "            base: {parent}::new({}),\n",
                parent_args.join(", ")
            ));

            for field in &info.fields {
                out.push_str(&format!("            {name}: {name},\n", name = field.name));
            }
            out.push_str("        }\n");
        } else {
            out.push_str("        Self {\n");
            for field in &info.fields {
                out.push_str(&format!("            {name}: {name},\n", name = field.name));
            }
            out.push_str("        }\n");
        }

        out.push_str("    }\n");
        out.push_str("}\n\n");
        out
    }

    fn generate_methods(&self, info: &ClassInfo) -> String {
        let mut out = String::new();
        out.push_str(&format!("impl {} {{\n", info.name));

        for method in &info.methods {
            let vis = if method.visibility == Visibility::Public {
                "pub "
            } else {
                ""
            };
            let params = self.format_method_params(method);
            let ret = self.format_return_type(method);

            out.push_str(&format!(
                "    {vis}fn {name}({params}){ret} {{\n",
                name = method.name
            ));
            out.push_str("        todo!(\"method body\")\n");
            out.push_str("    }\n");
        }

        out.push_str("}\n\n");
        out
    }

    fn generate_trait_impl(&self, class: &ClassInfo, trait_info: &TraitInfo) -> String {
        let mut out = String::new();
        out.push_str(&format!("impl {} for {} {{\n", trait_info.name, class.name));

        // Find class methods that match trait methods
        for trait_method in &trait_info.methods {
            let params = self.format_method_params(trait_method);
            let ret = self.format_return_type(trait_method);

            // Check if the class has an implementation
            let has_impl = class.methods.iter().any(|m| m.name == trait_method.name);

            if has_impl {
                out.push_str(&format!(
                    "    fn {name}({params}){ret} {{\n",
                    name = trait_method.name
                ));
                out.push_str("        todo!(\"trait method body\")\n");
                out.push_str("    }\n");
            } else if !trait_method.has_default_body {
                // Required method not implemented — emit a stub
                out.push_str(&format!(
                    "    fn {name}({params}){ret} {{\n",
                    name = trait_method.name
                ));
                out.push_str("        unimplemented!(\"required trait method\")\n");
                out.push_str("    }\n");
            }
            // Methods with default bodies are inherited, no need to emit
        }

        out.push_str("}\n\n");
        out
    }

    fn generate_writ_object_impl(&self, info: &ClassInfo, registry: &TypeRegistry) -> String {
        let mut out = String::new();

        out.push_str(&format!("impl WritObject for {} {{\n", info.name));

        // type_name()
        out.push_str(&format!(
            "    fn type_name(&self) -> &str {{ \"{}\" }}\n\n",
            info.name
        ));

        // get_field()
        let all_fields = registry.all_fields(&info.name);
        out.push_str("    fn get_field(&self, name: &str) -> Result<Value, String> {\n");
        out.push_str("        match name {\n");
        for field in &all_fields {
            out.push_str(&format!(
                "            \"{name}\" => Ok(self.{name}.clone().into()),\n",
                name = field.name
            ));
        }
        out.push_str(&format!(
            "            _ => Err(format!(\"'{}' has no field '{{}}'\", name)),\n",
            info.name
        ));
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        // set_field()
        out.push_str(
            "    fn set_field(&mut self, name: &str, value: Value) -> Result<(), String> {\n",
        );
        out.push_str("        match name {\n");
        for field in &all_fields {
            out.push_str(&format!(
                "            \"{name}\" => {{ self.{name} = value.try_into().map_err(|e: String| e)?; Ok(()) }}\n",
                name = field.name
            ));
        }
        out.push_str(&format!(
            "            _ => Err(format!(\"'{}' has no field '{{}}'\", name)),\n",
            info.name
        ));
        out.push_str("        }\n");
        out.push_str("    }\n\n");

        // call_method()
        out.push_str(
            "    fn call_method(&mut self, name: &str, _args: &[Value]) -> Result<Value, String> {\n",
        );
        out.push_str(&format!(
            "        Err(format!(\"'{}' has no native method '{{}}'\", name))\n",
            info.name
        ));
        out.push_str("    }\n\n");

        // as_any()
        out.push_str("    fn as_any(&self) -> &dyn std::any::Any {\n");
        out.push_str("        self\n");
        out.push_str("    }\n");

        out.push_str("}\n\n");
        out
    }

    fn format_method_params(&self, method: &MethodInfo) -> String {
        let mut parts = vec!["&mut self".to_string()];
        for (i, ty) in method.params.iter().enumerate() {
            parts.push(format!("arg{i}: {}", writ_type_to_rust(ty)));
        }
        parts.join(", ")
    }

    fn format_return_type(&self, method: &MethodInfo) -> String {
        if method.return_type == Type::Void {
            String::new()
        } else {
            format!(" -> {}", writ_type_to_rust(&method.return_type))
        }
    }

    fn collect_parent_fields(&self, info: &ClassInfo, registry: &TypeRegistry) -> Vec<FieldInfo> {
        let all = registry.all_fields(&info.name);
        let own_names: std::collections::HashSet<&str> =
            info.fields.iter().map(|f| f.name.as_str()).collect();
        all.into_iter()
            .filter(|f| !own_names.contains(f.name.as_str()))
            .collect()
    }

    /// Returns class names in topological order (parents before children).
    fn topological_class_order(&self, registry: &TypeRegistry) -> Vec<String> {
        let mut names: Vec<String> = registry.class_names().map(|s| s.to_string()).collect();
        names.sort();

        let mut ordered = Vec::new();
        let mut visited = std::collections::HashSet::new();

        for name in &names {
            self.topo_visit(name, registry, &mut ordered, &mut visited);
        }

        ordered
    }

    fn topo_visit(
        &self,
        name: &str,
        registry: &TypeRegistry,
        ordered: &mut Vec<String>,
        visited: &mut std::collections::HashSet<String>,
    ) {
        if visited.contains(name) {
            return;
        }
        visited.insert(name.to_string());

        // Visit parent first
        if let Some(info) = registry.get_class(name)
            && let Some(ref parent) = info.parent
        {
            self.topo_visit(parent, registry, ordered, visited);
        }

        ordered.push(name.to_string());
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use writ_parser::Visibility;
    use writ_types::{ClassInfo, FieldInfo, MethodInfo, TraitInfo, TypeRegistry};

    fn make_registry() -> TypeRegistry {
        let mut reg = TypeRegistry::new();

        // Register Entity (base class)
        reg.register_class(ClassInfo {
            name: "Entity".to_string(),
            fields: vec![
                FieldInfo {
                    name: "x".to_string(),
                    ty: Type::Float,
                    visibility: Visibility::Public,
                    has_default: true,
                    has_setter: false,
                },
                FieldInfo {
                    name: "y".to_string(),
                    ty: Type::Float,
                    visibility: Visibility::Public,
                    has_default: true,
                    has_setter: false,
                },
            ],
            methods: vec![],
            parent: None,
            traits: vec![],
        });

        // Register Player (extends Entity)
        reg.register_class(ClassInfo {
            name: "Player".to_string(),
            fields: vec![FieldInfo {
                name: "health".to_string(),
                ty: Type::Float,
                visibility: Visibility::Public,
                has_default: true,
                has_setter: false,
            }],
            methods: vec![MethodInfo {
                name: "takeDamage".to_string(),
                params: vec![Type::Float],
                return_type: Type::Void,
                is_static: false,
                visibility: Visibility::Public,
                has_default_body: false,
            }],
            parent: Some("Entity".to_string()),
            traits: vec![],
        });

        reg
    }

    #[test]
    fn generates_struct_with_deref() {
        let codegen = RustCodegen::new();
        let registry = make_registry();
        let output = codegen.generate(&registry);

        // Entity struct should be generated
        assert!(output.contains("pub struct Entity {"));
        assert!(output.contains("pub x: f32"));
        assert!(output.contains("pub y: f32"));

        // Player struct should have base field
        assert!(output.contains("pub struct Player {"));
        assert!(output.contains("base: Entity,"));
        assert!(output.contains("pub health: f32"));

        // Deref impls
        assert!(output.contains("impl std::ops::Deref for Player"));
        assert!(output.contains("type Target = Entity"));
        assert!(output.contains("impl std::ops::DerefMut for Player"));
    }

    #[test]
    fn generates_constructor() {
        let codegen = RustCodegen::new();
        let registry = make_registry();
        let output = codegen.generate(&registry);

        // Entity constructor
        assert!(output.contains("impl Entity {"));
        assert!(output.contains("pub fn new(x: f32, y: f32) -> Self"));

        // Player constructor takes parent fields + own fields
        assert!(output.contains("pub fn new(x: f32, y: f32, health: f32) -> Self"));
        assert!(output.contains("base: Entity::new(x, y)"));
    }

    #[test]
    fn generates_writ_object_impl() {
        let codegen = RustCodegen::new();
        let registry = make_registry();
        let output = codegen.generate(&registry);

        assert!(output.contains("impl WritObject for Entity"));
        assert!(output.contains("impl WritObject for Player"));
        assert!(output.contains("fn type_name(&self) -> &str { \"Player\" }"));
    }

    #[test]
    fn topological_order_parents_first() {
        let codegen = RustCodegen::new();
        let registry = make_registry();
        let order = codegen.topological_class_order(&registry);

        let entity_pos = order.iter().position(|n| n == "Entity").unwrap();
        let player_pos = order.iter().position(|n| n == "Player").unwrap();
        assert!(entity_pos < player_pos, "Entity should come before Player");
    }

    #[test]
    fn trait_codegen() {
        let mut reg = TypeRegistry::new();
        reg.register_trait(TraitInfo {
            name: "Damageable".to_string(),
            methods: vec![
                MethodInfo {
                    name: "takeDamage".to_string(),
                    params: vec![Type::Float],
                    return_type: Type::Void,
                    is_static: false,
                    visibility: Visibility::Public,
                    has_default_body: false,
                },
                MethodInfo {
                    name: "die".to_string(),
                    params: vec![],
                    return_type: Type::Void,
                    is_static: false,
                    visibility: Visibility::Public,
                    has_default_body: true,
                },
            ],
        });

        let codegen = RustCodegen::new();
        let output = codegen.generate(&reg);

        assert!(output.contains("pub trait Damageable {"));
        assert!(output.contains("fn takeDamage(&mut self, arg0: f32);"));
        assert!(output.contains("fn die(&mut self) {"));
    }
}
